# Generated by Django 5.0.3 on 2024-05-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Des_title", models.CharField(max_length=150)),
                ("Des_latitude_number", models.CharField(max_length=150)),
                ("Des_longitude_number", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "destination",
            },
        ),
        migrations.CreateModel(
            name="DestinationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Desimage",
                    models.FileField(
                        default="avatar.png", upload_to="upload/distation_img/"
                    ),
                ),
                ("Des_description", models.TextField(max_length=500)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destination_app.master",
                    ),
                ),
            ],
            options={
                "db_table": "destation_details",
            },
        ),
    ]
